# Generated by Django 4.2 on 2023-04-30 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
